-- VectorCAST 6.0 (%H%)
-- Test Case Script
-- 
-- Environment    : TUTORIAL_ADA
-- Unit(s) Under Test: MANAGER
-- 
-- Script Features
TEST.SCRIPT_FEATURE:ADA_DIRECT_ARRAY_INDEXING
TEST.SCRIPT_FEATURE:MULTIPLE_UUT_SUPPORT
--

-- Unit: MANAGER

-- Subprogram: PLACE_ORDER

-- Test Case: PLACE_ORDER.001
TEST.UNIT:MANAGER
TEST.SUBPROGRAM:PLACE_ORDER
TEST.NEW
TEST.NAME:PLACE_ORDER.001
TEST.NOTES:
This test is the same as the one created by following all of
the steps in the "Ada Tutorials -> Basic Tutorial" from the
VectorCAST Getting Started manual.

It shows the basic concepts associated with setting input and
expected values for both the Unit Under Test and Stub Functions.
TEST.END_NOTES:
TEST.VALUE:MANAGER.PLACE_ORDER.TABLE:2
TEST.VALUE:MANAGER.PLACE_ORDER.SEAT:1
TEST.VALUE:MANAGER.PLACE_ORDER.ORDER.SOUP:ONION
TEST.VALUE:MANAGER.PLACE_ORDER.ORDER.SALAD:CAESAR
TEST.VALUE:MANAGER.PLACE_ORDER.ORDER.ENTREE:STEAK
TEST.VALUE:MANAGER.PLACE_ORDER.ORDER.BEVERAGE:MIXED_DRINK
TEST.VALUE:DATABASE.GET_TABLE_RECORD.DATA.NUMBER_IN_PARTY:0
TEST.VALUE:DATABASE.GET_TABLE_RECORD.DATA.CHECK_TOTAL:0
TEST.EXPECTED:DATABASE.UPDATE_TABLE_RECORD.DATA.IS_OCCUPIED:TRUE
TEST.EXPECTED:DATABASE.UPDATE_TABLE_RECORD.DATA.NUMBER_IN_PARTY:1
TEST.EXPECTED:DATABASE.UPDATE_TABLE_RECORD.DATA.ORDER(1).DESSERT:PIE
TEST.EXPECTED:DATABASE.UPDATE_TABLE_RECORD.DATA.CHECK_TOTAL:12..16
TEST.END
